const data = {
  products: [
    {
      name: 'Martin D-35',
      slug: 'martin-d-35',
      category: 'acoustic',
      image: '/images/martind35.jpg',
      price: 258000,
      countInstock: 2,
      brand: 'Martin',
      rating: 4.5,
      numReviews: 10,
      description: 'Classic Dreadnought Shaped Martin!',
    },
    {
      name: 'Lowden F32',
      slug: 'lowden-f-32',
      category: 'acoustic',
      image: '/images/lowdenlast.jpg',
      price: 324000,
      countInstock: 5,
      brand: 'Lowden',
      rating: 5,
      numReviews: 10,
      description: 'Award Winning Musical Instrument, pride of ireland!',
    },
    {
      name: 'Lowden F32C',
      slug: 'lowden-f-32-c',
      category: 'acoustic',
      image: '/images/lowden32c.jpg',
      price: 343000,
      countInstock: 4,
      brand: 'lowden',
      rating: 4.5,
      numReviews: 10,
      description: 'The brother of the renowned F32',
    },
    {
      name: 'Lowden F50',
      slug: 'lowden-f-50',
      category: 'acoustic',
      image: '/images/lowdenf50.jpg',
      price: 497900,
      countInstock: 3,
      brand: 'lowden',
      rating: 4.5,
      numReviews: 10,
      description: "Newest addition to lowden's F series!",
    },
  ],
};
export default data;
